[package]
name = "audio"
version = "0.1.0"
edition = "2024"

[dependencies]
alsa = "0.9"
opus = "0.3"
log = "0.4"
anyhow = "1.0"
tokio = { version = "1", features = ["sync"] }

[build-dependencies]
pkg-config = "0.3"
